<h1>Create NumPy arrays using Python's "array like" data types</h1>


In [1]:
import numpy as np 
print(np.__version__)

1.16.4


In [2]:
my_list = [-17, 0, 4, 5, 29]
np_array=np.array(my_list)
print(np_array) 

[-17   0   4   5  29]


## multiply * works differently between python types and np typy

In [3]:
my_list_10x=my_list*10
print(my_list_10x)
np_array_10x=np_array*10
print(np_array_10x)

[-17, 0, 4, 5, 29, -17, 0, 4, 5, 29, -17, 0, 4, 5, 29, -17, 0, 4, 5, 29, -17, 0, 4, 5, 29, -17, 0, 4, 5, 29, -17, 0, 4, 5, 29, -17, 0, 4, 5, 29, -17, 0, 4, 5, 29, -17, 0, 4, 5, 29]
[-170    0   40   50  290]


##complex and tuple

In [0]:
tupleToNumpy=(14, -3.14, 4+3j); tupleToNumpy2=(-14, 3.21)  #int, float, complex, np array keeps elements of array uniform
numpyFromTuple=np.array(tupleToNumpy)
numpyFromTuple2=np.array(tupleToNumpy2)
print(numpyFromTuple)
print(numpyFromTuple2)


[14.  +0.j -3.14+0.j  4.  +3.j]
[-14.     3.21]


##simple methods

In [5]:
# numpy.arange([start, ]stop, [step, ]dtype=None) official url by google np.arange
np.arange(10,30,2)*10-3

array([ 97, 117, 137, 157, 177, 197, 217, 237, 257, 277])

In [14]:
np.arange(20,step=4)

array([ 0,  4,  8, 12, 16])

In [8]:
nparray=(np.arange(10,30,2)-3)*10
nparray

array([ 70,  90, 110, 130, 150, 170, 190, 210, 230, 250])

In [10]:
nparray.size

10

In [13]:
nparray.shape((2,5))

TypeError: ignored