<h1>Create NumPy arrays using Python's "array like" data types</h1>


In [1]:
import numpy as np 
print(np.__version__)

1.16.4


In [2]:
my_list = [-17, 0, 4, 5, 29]
np_array=np.array(my_list)
print(np_array) 

[-17   0   4   5  29]


## multiply * works differently between python types and np typy

In [3]:
my_list_10x=my_list*10
print(my_list_10x)
np_array_10x=np_array*10
print(np_array_10x)

[-17, 0, 4, 5, 29, -17, 0, 4, 5, 29, -17, 0, 4, 5, 29, -17, 0, 4, 5, 29, -17, 0, 4, 5, 29, -17, 0, 4, 5, 29, -17, 0, 4, 5, 29, -17, 0, 4, 5, 29, -17, 0, 4, 5, 29, -17, 0, 4, 5, 29]
[-170    0   40   50  290]


##complex and tuple

In [0]:
tupleToNumpy=(14, -3.14, 4+3j); tupleToNumpy2=(-14, 3.21)  #int, float, complex, np array keeps elements of array uniform
numpyFromTuple=np.array(tupleToNumpy)
numpyFromTuple2=np.array(tupleToNumpy2)
print(numpyFromTuple)
print(numpyFromTuple2)


[14.  +0.j -3.14+0.j  4.  +3.j]
[-14.     3.21]


##simple methods

In [5]:
# numpy.arange([start, ]stop, [step, ]dtype=None) official url by google np.arange
np.arange(10,30,2)*10-3

array([ 97, 117, 137, 157, 177, 197, 217, 237, 257, 277])

In [14]:
np.arange(20,step=4)

array([ 0,  4,  8, 12, 16])

In [8]:
nparray=(np.arange(10,30,2)-3)*10
nparray

array([ 70,  90, 110, 130, 150, 170, 190, 210, 230, 250])

In [10]:
nparray.size

10

In [15]:
np.linspace(0,30,10,True)

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        , 23.33333333, 26.66666667, 30.        ])

##indexing, shaping (dimension) and slicing

In [16]:
z=np.zeros(20)
z[10]

0.0

In [24]:
z[10]=9;z[0]=10; z[-1]=7.5; z[-2]=-2.1
z

array([10. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  9. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. , -2.1,  7.5])

In [19]:
o=np.ones((3,3), dtype=int)
o

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [26]:
z.shape=(4,5)
z

array([[10. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ],
       [ 9. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. , -2.1,  7.5]])

In [28]:
z.shape=(2,2,5)   #3-d np array
z

array([[[10. ,  0. ,  0. ,  0. ,  0. ],
        [ 0. ,  0. ,  0. ,  0. ,  0. ]],

       [[ 9. ,  0. ,  0. ,  0. ,  0. ],
        [ 0. ,  0. ,  0. , -2.1,  7.5]]])

In [31]:
z[1][1]

array([ 0. ,  0. ,  0. , -2.1,  7.5])

In [36]:
z[1,0][0]

9.0

In [32]:
z[0]

array([[10.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

## boolean mask array

In [37]:
nparray

array([ 70,  90, 110, 130, 150, 170, 190, 210, 230, 250])

In [39]:
can_div_35_mask = 0 == (nparray % 35)
can_div_35_mask

array([ True, False, False, False, False, False, False,  True, False,
       False])

In [41]:
filtered_nparray = nparray[can_div_35_mask]
filtered_nparray

array([ 70, 210])

In [42]:
further_filtered_nparray=filtered_nparray[filtered_nparray>70]
further_filtered_nparray

array([210])